### PR TITLE
cleaning

### PR DESCRIPTION
**Pull request by brohrer-ms**
I tried to git rm all the undesirable files. There are still a handful of placeholder.md files in otherwise empty directories in order to maintain the directory structure.

### CODE REVIEW

**Comment by jflam** [comment]
I just noticed (after committing the PR) that you also deleted all of the project files as well. Was that intentional? We really should have these files in RTVS projects.

**Comment by brohrer-ms** [comment]
Shoot. I overdid it. Thanks John. Which file extension am I looking to keep? *.rproj? *.rxproj?

I’m still coming up to speed on Visual Studio and R both. Thanks for your help.

Brandon

**Comment by brohrer-ms** [comment]
You’ll also need the .sln file as well that binds them all together.

From: Brandon Rohrer
Sent: Wednesday, February 17, 2016 12:58 PM
To: Microsoft/RTVS-docs <reply@reply.github.com>; Microsoft/RTVS-docs <RTVS-docs@noreply.github.com>; John Lam (AZURE) <jflam@microsoft.com>
Subject: RE: [RTVS-docs] cleaning (#6)

Shoot. I overdid it. Thanks John. Which file extension am I looking to keep? *.rproj? *.rxproj?

I’m still coming up to speed on Visual Studio and R both. Thanks for your help.

Brandon

**Comment by smortaz** [comment]
have you tried the VS git add-in?  it might work well for this.

**Pull request merged**
